# Generated by Django 5.0.4 on 2024-04-18 02:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='seccion1',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
