# Generated by Django 5.0.4 on 2024-04-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_seccion1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='seccion1',
            new_name='body2',
        ),
    ]
